version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  sonarcloud: sonarsource/sonarcloud@1.0.3
  
jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
      
workflows:
  main:
    jobs:
      - build:
          context: Publishing Orb
          orb-ref: sonarsource/sonarcloud@1.0.3
