version: 2
orbs:
  maven: circleci/maven@1.0
jobs:
  maven_test:
    jobs:
      - maven/test
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run : mvn test package
      - store_artifacts:
          path:  target
